### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by JonhSilver** [checkout/checkout-sdk-python#69]
Where to get this keys? Which steps i should go to find them? Cant found them at all

For Default account systems: CHECKOUT_PUBLIC_KEY & CHECKOUT_SECRET_KEY
For Four account systems: CHECKOUT_FOUR_PUBLIC_KEY & CHECKOUT_FOUR_SECRET_KEY
For Four account systems (OAuth): CHECKOUT_FOUR_OAUTH_CLIENT_ID & CHECKOUT_FOUR_OAUTH_CLIENT_SECRET

**Comment by Armando-Ibarra** [comment]
Hi @JonhSilver 
You must request a test account, you can do it from this link
https://www.checkout.com/get-test-account

And this is the FAQ if you found any other issue
https://www.checkout.com/docs/faq/my-account

If you have any question please let us know

**Comment by JonhSilver** [comment]
I dont need test account, i need know place where i can see thoose keys

**Comment by Armando-Ibarra** [comment]
Did you already have a Checkout account?
Did you already contact your customer support specialist?
All those information is shared by your account, actually you can't get Default/Four accounts at the same time, like I said depending on your company needs you'll get all those details.

**Comment by JonhSilver** [comment]
Did you already have a Checkout account? Yes
Did you already contact your customer support specialist? Yes, they dont know anything

**Comment by Armando-Ibarra** [comment]
@JonhSilver I understand the situation now.
I already asked to the team to reach out to you to helping on getting the credentials information.

If you log into your account, and click on Developer's tab -> Keys, you should be able to see all the keys that your account have.

![image](https://user-images.githubusercontent.com/30295119/173856965-22eea4d3-38cc-4513-9a6b-76bc091b1ea6.png)

Public and Secret key is unique on each account, so for example let's say you have an account for Four systems, then you need to instantiate the SDK like 
`checkout_sdk.FourSdk() \
  .secret_key(os.environ.get('CHECKOUT_FOUR_SECRET_KEY')) \
  .public_key(os.environ.get('CHECKOUT_FOUR_PUBLIC_KEY')) \. # public key is optional because is only needed for tokens module
  .build()`

**Comment by JonhSilver** [comment]
Yep, ty, but problem is that in my account they called just Keys (not CHECKOUT_FOUR_PUBLIC_KEY  or CHECKOUT_FOUR_OAUTH_CLIENT_ID ), but in script they have a lot of names

For Default account systems: CHECKOUT_PUBLIC_KEY & CHECKOUT_SECRET_KEY
For Four account systems: CHECKOUT_FOUR_PUBLIC_KEY & CHECKOUT_FOUR_SECRET_KEY
For Four account systems (OAuth): CHECKOUT_FOUR_OAUTH_CLIENT_ID & CHECKOUT_FOUR_OAUTH_CLIENT_SECRET
How to know which account Key meet Default or Four key name in script?

**Comment by Armando-Ibarra** [comment]
I can't tell if in the UI there is something that says the type of your account, but we can follow the pattern of the key.

**Comment by Armando-Ibarra** [comment]
I can't tell if in the UI there is something that says the type of your account, but we can follow the pattern of the key.

For Default the key should look like
sk_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX OR matches this regex `^sk_(test_)?(\\w{8})-(\\w{4})-(\\w{4})-(\\w{4})-(\\w{12})$`

Four SDK should look like
sk_XXXXXXXXXXXXXXXXXXXXXX or matches this pattern `^sk_(sbox_)?[a-z2-7]{26}[a-z2-7*#$=]$`

Try this page for easy regex https://regex101.com/

Oauth keys are more easier because 
client_id starts with `ack_.....` and client_secret well is a huge string

Four keys and OAUTH are the same system type so consider the system as this way

Default -> Is the old version of the Checkout systems, basically customers that have been enrolled in checkout for a long time.
Four & OAUTH -> is the newest version of Checkout systems, if your account is recently created is probably that is enrolled on this system, this will be the only version available in the future (not near)

**Comment by JonhSilver** [comment]
Also we dont have developer mode in our hubs accounts :(
![image](https://user-images.githubusercontent.com/24619483/174016694-8aba5184-be01-4134-ab19-bf5ae455af41.png)

**Comment by Armando-Ibarra** [comment]
Okay, I already escalate this and sorry for not having a clear response about how to get those keys I will circle back to you whenever I have the procedure.

**Comment by Armando-Ibarra** [comment]
@JonhSilver is there anything else we can help? otherwise I'll close this issue.
